package edu.umb.cs.tinydds.cl;

/* Generated By:JavaCC: Do not edit this line. DDSParserConstants.java */
public interface DDSParserConstants {

  int EOF = 0;
  int PHENOM = 5;
  int AND = 6;
  int OR = 7;
  int LPAREN = 8;
  int RPAREN = 9;
  int EQUALS = 10;
  int NOTEQUAL = 11;
  int LT = 12;
  int GT = 13;
  int NUMBER = 14;
  int ATOM = 15;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"Phenom:\"",
    "\"and\"",
    "\"or\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"<>\"",
    "\"<\"",
    "\">\"",
    "<NUMBER>",
    "<ATOM>",
  };

}
