package edu.umb.cs.tinydds.cl;

/* Generated By:JavaCC: Do not edit this line. DDSParser.java */
//import java.io.StringReader;
import java.io.ByteArrayInputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.util.Hashtable;

public class DDSParser implements DDSParserConstants {

        private static String phenom;

        public DDSParser(String s){
                this(new InputStreamReader(new ByteArrayInputStream(s.getBytes())));
        }

        public static void main(String[] args){

                try {
                        String query = args[0];
                        DDSParser parser = new DDSParser(query);
                        Expression exp = parser.parse();

                        Hashtable vars = new Hashtable();
                        vars.put("Phenom:temp", "5.0");

                        boolean result = exp.eval(vars);
                        System.out.println("result: "+result);
                }
                catch(Exception e){
                        e.printStackTrace();
                }
        }

        public String getPhenom(){
                return this.phenom;
        }

        //public boolean evaluate(Hashtable variables){
        //	return this.rootExpression.eval(variables);
        //}

        public interface Expression {
                  public boolean eval(Hashtable vars);
        }

        static class AndOrExpression implements Expression {

               private Expression lhs;
               private Expression rhs;
               private String operator;

               public AndOrExpression(Expression lhs, Expression rhs, String operator){
                      this.lhs = lhs;
                      this.rhs = rhs;
                      this.operator = operator;
               }

               public boolean eval(Hashtable vars){
                      return true;
               }
        }

        static class RelationalExpression implements Expression {

                private String lhs;
                private String rhs;
                private String operator;
                private boolean lhsIsVar;

                public RelationalExpression(String lhs, String rhs, String operator, boolean lhsIsVar){
                        this.lhs = lhs;
                        this.rhs = rhs;
                        this.operator = operator;
                        this.lhsIsVar = lhsIsVar;

                        //System.out.println("lhs: "+lhs);
                        //System.out.println("rhs: "+rhs);
                        //System.out.println("operator: "+operator);
                }

                public boolean eval(Hashtable vars){

                        double lhsValue;
                        double rhsValue;

                        if(lhsIsVar){
                            String lhsValueString = (String)vars.get(lhs);
                            lhsValue = Double.parseDouble(lhsValueString);
                            rhsValue = Double.parseDouble(rhs);
                        }
                        else {
                            String rhsValueString = (String)vars.get(rhs);
                            rhsValue = Double.parseDouble(rhsValueString);
                            lhsValue = Double.parseDouble(lhs);
                        }


                        if(operator.equals(">")){
                                return lhsValue > rhsValue;
                        }
                        else if(operator.equals("<")){
                                return lhsValue < rhsValue;
                        }
                        else if(operator.equals("=")){
                                return lhsValue == rhsValue;
                        }
                        else if(operator.equals("<>")){
                                return lhsValue != rhsValue;
                        }
                        else
                                return false;

                }
        }

  static final public Expression parse() throws ParseException {
        Expression exp = null;
    exp = expression();
         {if (true) return exp;}
    throw new Error("Missing return statement in function");
  }

  static final public Expression expression() throws ParseException {
        Expression lhs = null, rhs = null;
    lhs = condition();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
      case OR:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        jj_consume_token(AND);
        rhs = condition();
                                      lhs = new AndOrExpression(lhs, rhs, "&&");
        break;
      case OR:
        jj_consume_token(OR);
        rhs = condition();
                                     lhs = new AndOrExpression(lhs, rhs, "||");
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
          {if (true) return lhs;}
    throw new Error("Missing return statement in function");
  }

  static final public Expression condition() throws ParseException {
        Expression exp;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PHENOM:
    case NUMBER:
      exp = phenom();
      break;
    case LPAREN:
      jj_consume_token(LPAREN);
      exp = expression();
      jj_consume_token(RPAREN);
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return exp;}
    throw new Error("Missing return statement in function");
  }

  static final public Expression phenom() throws ParseException {
        Token tPhenom, tOp, tNum;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PHENOM:
      jj_consume_token(PHENOM);
      tPhenom = jj_consume_token(ATOM);
      tOp = relationalOp();
      tNum = jj_consume_token(NUMBER);
          {if (true) return new RelationalExpression("Phenom:"+tPhenom.image, tNum.image, tOp.image, true);}
      break;
    case NUMBER:
      tNum = jj_consume_token(NUMBER);
      tOp = relationalOp();
      jj_consume_token(PHENOM);
      tPhenom = jj_consume_token(ATOM);
          {if (true) return new RelationalExpression(tNum.image, "Phenom:"+tPhenom.image, tOp.image, false);}
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public Token relationalOp() throws ParseException {
        Token tOp;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQUALS:
      tOp = jj_consume_token(EQUALS);
      break;
    case LT:
      tOp = jj_consume_token(LT);
      break;
    case GT:
      tOp = jj_consume_token(GT);
      break;
    case NOTEQUAL:
      tOp = jj_consume_token(NOTEQUAL);
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return tOp;}
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_initialized_once = false;
  static public DDSParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  static public Token token, jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[5];
  static private int[] jj_la1_0;
  static {
      jj_la1_0();
   }
   private static void jj_la1_0() {
      jj_la1_0 = new int[] {0xc0,0xc0,0x4120,0x4020,0x3c00,};
   }

  public DDSParser(java.io.InputStream stream) {
     this(stream, null);
  }
  public DDSParser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e.toString()); }
    token_source = new DDSParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e.toString()); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  public DDSParser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new DDSParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  public DDSParser(DDSParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  public void ReInit(DDSParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  static final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.Vector jj_expentries = new java.util.Vector();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  static public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[16];
    for (int i = 0; i < 16; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 5; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 16; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  static final public void enable_tracing() {
  }

  static final public void disable_tracing() {
  }

}
