package edu.umb.cs.tinydds.cl;

/* Generated By:JavaCC: Do not edit this line. DDSParserConstants.java */
public interface DDSParserConstants {

  int EOF = 0;
  int PHENOM = 5;
  int TEMPORAL = 6;
  int BEFORE = 7;
  int AFTER = 8;
  int BETWEEN = 9;
  int AND = 10;
  int OR = 11;
  int LPAREN = 12;
  int RPAREN = 13;
  int EQUALS = 14;
  int NOTEQUAL = 15;
  int LT = 16;
  int GT = 17;
  int COMMA = 18;
  int NATURALNUM = 19;
  int REALNUM = 20;
  int REALPART = 21;
  int ATOM = 22;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"Phenom\"",
    "\"Temporal\"",
    "<BEFORE>",
    "<AFTER>",
    "<BETWEEN>",
    "<AND>",
    "<OR>",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"<>\"",
    "\"<\"",
    "\">\"",
    "\",\"",
    "<NATURALNUM>",
    "<REALNUM>",
    "<REALPART>",
    "<ATOM>",
  };

}
